# Introduction to Numpy and Pandas

## Where we are going to end up

In [1]:
# Importing in packages
import pandas as pd
import numpy as np
from pandas import DataFrame, Series

In [2]:
basedf = pd.read_csv('csv_hil/ss13hil.csv')

In [3]:
# Separate the read-in and the output, don't want to read in the data every run
# Print out the columns in the dataframe
print(list(basedf.columns))

['insp', 'RT', 'SERIALNO', 'DIVISION', 'PUMA00', 'PUMA10', 'REGION', 'ST', 'ADJHSG', 'ADJINC', 'WGTP', 'NP', 'TYPE', 'ACR', 'AGS', 'BATH', 'BDSP', 'BLD', 'BUS', 'CONP', 'ELEP', 'FS', 'FULP', 'GASP', 'HFL', 'MHP', 'MRGI', 'MRGP', 'MRGT', 'MRGX', 'REFR', 'RMSP', 'RNTM', 'RNTP', 'RWAT', 'RWATPR', 'SINK', 'SMP', 'STOV', 'TEL', 'TEN', 'TOIL', 'VACS', 'VALP', 'VEH', 'WATP', 'YBL', 'FES', 'FINCP', 'FPARC', 'GRNTP', 'GRPIP', 'HHL', 'HHT', 'HINCP', 'HUGCL', 'HUPAC', 'HUPAOC', 'HUPARC', 'KIT', 'LNGI', 'MULTG', 'MV', 'NOC', 'NPF', 'NPP', 'NR', 'NRC', 'OCPIP', 'PARTNER', 'PLM', 'PSF', 'R18', 'R60', 'R65', 'RESMODE', 'SMOCP', 'SMX', 'SRNT', 'SVAL', 'TAXP', 'WIF', 'WKEXREL', 'WORKSTAT', 'FACRP', 'FAGSP', 'FBATHP', 'FBDSP', 'FBLDP', 'FBUSP', 'FCONP', 'FELEP', 'FFSP', 'FFULP', 'FGASP', 'FHFLP', 'FINSP', 'FKITP', 'FMHP', 'FMRGIP', 'FMRGP', 'FMRGTP', 'FMRGXP', 'FMVP', 'FPLMP', 'FREFRP', 'FRMSP', 'FRNTMP', 'FRNTP', 'FRWATP', 'FRWATPRP', 'FSINKP', 'FSMP', 'FSMXHP', 'FSMXSP', 'FSTOVP', 'FTAXP', 'FTELP', 'F

In [4]:
# How many rows are there in the dataframe
basedf.shape[0]

287799

In [5]:
# How many columns are there in the dataframe
basedf.shape[1]

205

For more information about each of the columns, can go to:

https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMS_Data_Dictionary_2009-2013.pdf?#

### How correlated is the number of bedrooms (BDSP), the total number of rooms (RMSP) and the number of persons listed (NP) by PUMA? We need to incorperate replication weights into our regression and repeat it for every PUMA. How do we do this in any reasonable amount of time?

Before we get to solving this we'll go over the basics of numpy and pandas.

## Numpy Data Structures and Sample Data Generation

### Theory

- Numpy is can be thought of as a MATLAB like analysis tool
- If you can frame your problem in terms of matrix algebra then numpy is your friend
- Some limitations:
    - single data-type per ndarray
    - can be all objects but this loses almost all the power of numpy
    - does not support query-like or JOIN-like operators that are familiar from working with other tables
    
- Examples of good ndarrays
    - Images
    - Raster-type maps
    - Markov transition matrices
    - etc.

#### Making a simple array

In [6]:

# create a list of ones
z1 = np.ones(4)
print('The shape of z1 is:' + str(z1.shape))
print('z1 has dimensionality of: ' + str(z1.ndim))

# create a matrix of ones
z2 = np.ones((4, 4))
print('The shape of z2 is:' + str(z2.shape))
print('z2 has dimensionality of: ' + str(z2.ndim))

The shape of z1 is:(4,)
z1 has dimensionality of: 1
The shape of z2 is:(4, 4)
z2 has dimensionality of: 2


#### Create an identiy matrix

In [7]:
a = np.eye(4)
print(a.dtype)

# convert to booleans
a = a.astype(np.bool)
print(a)

print(a.dtype)


float64
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
bool


#### Create an ndarray manually

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.ndim)
print(a)


2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Change row 1 of the array, remember that python counts from 0
a[1] = [4, 5, 7]
print(a)


[[1 2 3]
 [4 5 7]
 [7 8 9]]


In [10]:
# Change element [1,2] in the array
a[1, 2] = 13
print(a)


[[ 1  2  3]
 [ 4  5 13]
 [ 7  8  9]]


#### Making an ndarray from randomly generated data

In [11]:
# Generate a randomly number in the range 0 - 25
a = np.random.normal(0, 25)
print(a)
print(type(a))

36.94657151658207
<class 'float'>


In [12]:
# Generate a random list
b = np.random.normal(0, 25, 5)
print(b)
print(type(b))

[-17.18049358  -1.34732906  -2.66192351 -30.44735632  11.2917333 ]
<class 'numpy.ndarray'>


In [13]:
# Generate a random matrix
c = np.random.normal(0, 25, (4, 4))
print(c)

[[ 16.33733775 -39.2337685   32.78643802 -20.11182555]
 [ 33.64839999 -31.42330753 -44.01739105  -0.81167363]
 [  2.4494349   -1.3325662  -11.44103642 -25.18390728]
 [  1.01832901  64.03900264  24.34075805 -32.16767564]]


#### Making an ndarray from a pandas Dataframe

In [14]:
basedf = pd.read_csv('csv_hil/ss13hil.csv')
colList = []
for n in range(1,81,1):
    colList.append('WGTP'+str(n))
    simpledf = basedf[colList]
    testArray = simpledf.iloc[0:80].values
print(type(testArray))

<class 'numpy.ndarray'>


### Problems 1

1) Generate a 100 x 100 identity matrix and set it to the variable i

In [15]:
i = np.eye(100)
print(i.shape)

(100, 100)


2) Swap the first and second rows (Hint: create two 1D arrays from the first two vectors using v1=i[0].copy() and v2=i[1].copy(), use these to change the values of the rows of i) What will this new matrix do if you matrix multiply it against a vector?

In [16]:
# defining the first two rows of the matrix
i0 = i[0].copy()
i1 = i[1].copy()

# swapping the two rows
modified_i = np.eye(100)
modified_i[0] = i1
modified_i[1] = i0

mat_mul = np.matmul(modified_i, i0)
print(mat_mul)

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


3) Use np.random.normal to generate a 500 row and 2 column matrix of random samples from a normal distribution with mean 1000 and standard deviation of 20

In [17]:
# np.random.normal?
random_norm = np.random.normal(loc=1000, scale=20, size=(500,2))
print(random_norm.shape)

(500, 2)


### Problems 2 

1) Use np.random.poisson (https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.poisson.html) to generate a 1000 random samples from a poisson distribution with an expected interval of 10

In [18]:
random_poisson = np.random.poisson(lam=10, size=1000)

2) Starting from basedf=pd.read csv(’ss13hil.csv’) use the data dictionary to identify the column names associated with the 2010 PUMA microdata area code, the housing weight, the number of units in structure, the tenure, and the vacancy status. Create a list of these codes as strings and name it listCols. Set df=basedf[listCols].copy() and then attempt to turn this into an ndarray. What is the inferred datatype? What are the number of rows? what are the number of columns?

In [19]:
basedf = pd.read_csv('csv_hil/ss13hil.csv')

In [20]:
listCols = ['PUMA00', 'WGTP', 'NP', 'TEN', 'VACS']
df = basedf[listCols].copy()

print(type(df))

numpy_df = np.array(df)

print("\n")
print("The ndarray datatype is:")
print(type(numpy_df))

print("\n")
print("The ndarray has a shape of (rows, columns)")
print(numpy_df.shape)

<class 'pandas.core.frame.DataFrame'>


The ndarray datatype is:
<class 'numpy.ndarray'>


The ndarray has a shape of (rows, columns)
(287799, 5)


### Element-wise Operations

- scalar multiplication (multiply every element by a number)
- element-wise reciprocal (replace every element by its inverse)
- element-wise exponentiation (raise every element to a power)
- unary universal functions (np.log, np.exp, np.isnan)
- binary universal functions (np.maximum, np.minimum)

In [21]:
# Element-wise operations
x = np.array([[1, 2], [3, 4]])

print('multiply all elements by 5')
print(x * 5)

multiply all elements by 5
[[ 5 10]
 [15 20]]


In [22]:
print('invert all elements')
print(1 / x)

invert all elements
[[1.         0.5       ]
 [0.33333333 0.25      ]]


In [23]:
print('take the square root of all elements')
print(x**0.5)

take the square root of all elements
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [24]:
print('take the natural log of all elements')
print(np.log(x))

take the natural log of all elements
[[0.         0.69314718]
 [1.09861229 1.38629436]]


In [25]:
# Replace an element with a NaN (not a number)
x = x.astype(np.float64)
x[0, 0] = np.nan
np.isnan(x)

array([[ True, False],
       [False, False]])

In [26]:
# Define a new matrix
y = np.array([[1.5, 2.5], [0, 0]])

# Find the maximum of two matrices
np.maximum(x, y)

array([[nan, 2.5],
       [3. , 4. ]])

### Transposition
- Transposition is a special kind of rearranging of elements
- Rows are switched with columns
- This operation is essential to much of linear algebra

In [27]:
x = np.array([[1, 2], [3, 4]])
print(x.T)

[[1 3]
 [2 4]]


### Matrix addition and other binary element-wise operations
- Matrices of the same size can be combined through element-wise arithmetic
- Addition and subtraction are the same as in usual matrix algebra
- Multiplication and division operate element-wise and so are not the same as matrix multiplication and factorization

In [28]:
# Define two matrices 

x = np.array([[1, 2], [3, 4]])
y = x*3

In [29]:
# matrix addition
x + y

array([[ 4,  8],
       [12, 16]])

In [30]:
# matrix subtraction
x - y

array([[-2, -4],
       [-6, -8]])

In [31]:
# matrix multiplication (element wise)
x * y

array([[ 3, 12],
       [27, 48]])

In [32]:
# matrix division (element wise)
x / y

array([[0.33333333, 0.33333333],
       [0.33333333, 0.33333333]])

In [33]:
y / x

array([[3., 3.],
       [3., 3.]])

### Matrix Multiplication and Matrix Inversion
- To access the traditional matrix product in numpy, use the np.dot() function
- This multiplies rows of the first matrix by columns of the second
- This only works if the row length of the first matrix agrees with the column length of the second

In [34]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[0, 1], [1, 0]])
np.dot(x, y)


array([[2, 1],
       [4, 3]])

- np.linalg package contains the function inv, which numerically computes the matrix inverse of a square matrix

In [35]:
x = np.array([[1, 2], [3, 4]])
x_inv = np.linalg.inv(x)
np.dot(x, x_inv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

- When applied to transposed 1D arrays it also can be used to calculate the inner product

In [36]:
x = np.array([[1, 2], [3, 4]])
y = np.array([0, 1])
np.dot(y, x)

array([3, 4])

In [37]:
z = np.array([0, 1]).T
np.dot(y, z)

1

In [38]:
z = np.array([1, 0]).T
np.dot(y, z)

0

### Advanced Linear Algebra
- In addition to matrix inversion, np.linalg contains a wide range of advanced functionality
- np.linalg.trace computes the sum of diagonal elements
- np.linalg.det computes the determinant of a matrix
- np.linalg.eig computes the eigenvectors and eigenvalues of a square matrix
- np.linalg.svd computes the singular value decomposition of a matrix
- np.linalg.solve computes the solution to a linear system of equations
- np.linal.lstsq computes the least squares solution to an overdetermined linear system
- np.linalg is so useful that if you are working with numpy at any length it is probably worth importing in its own right

### Problems 1

1) Use np.random.normal to generate a 10 by 10 matrix and save it to the variable x

In [39]:
x = np.random.normal(size=(10, 10))

2) The resulting matrix should have rank 10 with high probability. Confirm that it does with np.linalg.matrix rank(x). If it has Rank less than 10, re-generate the matrix until it does.

In [40]:
temp_x = np.random.normal(size=(10, 10))
rank = np.linalg.matrix_rank(temp_x)
if rank == 10:
    x = temp_x
else:
    temp_x = np.random.normal(size=(10, 10))

3) Compute the matrix inverse of your full rank matrix.

In [41]:
inv_x = np.linalg.inv(x)

4) Take the matrix product of your random matrix with its inverse and save that to a new variable id approx.

In [42]:
id_approx = np.dot(x, inv_x)
# print(id_approx)

5) Create a new 10 by 10 identity matrix.

In [43]:
identity = np.eye(10)

6) Subtract the new identity matrix from your id approx and save that to a new variable called inv error. (this is the error matrix relative to a perfect inversion)

In [44]:
inv_error = identity - id_approx
# print(inv_error)

### Problems 2

1) Compute the 2-norm of the inv error matrix using np.linalg.norm (see https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.linalg.norm.html) The result should be a very very small number

In [45]:
norm2 = np.linalg.norm(inv_error, ord=None)
print(norm2)

1.5781978950825534e-15


2) Repeat this process by using np.random.normal to generate a matrix with twice as many rows as columns. Confirm that its rank is equal to its number of columns.

In [46]:
big_rand = np.random.normal(size=(20,20))
print(np.linalg.matrix_rank(big_rand))

20


3) For this matrix produce a pseudoinverse using np.linalg.pinv and repeat the above analysis of how close the left matrix product is to an identity matrix. What about the right matrix product?

In [47]:
# Generate the pseudo inverse
pseudo_inv = np.linalg.pinv(big_rand)

# Calculate an approximate identity matrix by taking the dot product
big_id_approx = np.dot(big_rand, pseudo_inv)

# Find the error between the approximate and exact identity matrix
big_id = np.eye(20)
inv_error_big = big_id - big_id_approx

# Calculate the 2-norm of the inverse error matrix
big_norm = np.linalg.norm(inv_error_big, ord=None)
print(big_norm)

4.288848866182004e-14


## What is Pandas?
- Pandas provides a SQL-like approach (that blends in elements of statistics and linear algebra) to analyzing tables of data
- DataFrames in R are very similar
- Differences from NumPy: Pandas allows multiple datatypes, includes richer querying and merging of datasets
- Pandas has been adopted as a de facto standard for input and vectorization across numerous disciplines
- Spatial Data Analysis, Machine Learning, Natural Language Processing, Visualization and Mapping

### DataFrames and their Constructors
- Pandas includes both Series and DataFrame
- We will exclusively focus on DataFrames.
- Constructor and data load functions have three key options:
    - Column names and default column data types
    - Indexes or row names
    - NULL handling

#### Column oriented

In [48]:
dataDict = {'ID':[1000, 1212, 1357, 4908],
            'province':['AB', 'AB', 'BC', 'BC'],
            'income':[12000, 43000, 95000, 79500]}
df = DataFrame(dataDict)
df.head()

ID province  income
0  1000       AB   12000
1  1212       AB   43000
2  1357       BC   95000
3  4908       BC   79500

In [49]:
dataDict = {'ID':[1000, 1212, 1357, 4908],
            'province':['AB', 'AB', 'BC', 'BC'],
            'income':[12000, 43000, 95000, 79500]}
df = DataFrame(dataDict, index=dataDict['ID'])
df.head()

ID province  income
1000  1000       AB   12000
1212  1212       AB   43000
1357  1357       BC   95000
4908  4908       BC   79500

In [50]:
dataDict = {'ID':[1000, 1212, 1357, 4908],
            'province':['AB', 'AB', 'BC', 'BC'],
            'income':[12000, 43000, 95000, 79500]}
df = DataFrame(dataDict, index=dataDict['ID'],
               columns=['province', 'income'])
df.head()

province  income
1000       AB   12000
1212       AB   43000
1357       BC   95000
4908       BC   79500

#### Row-oriented

In [51]:
r1 = {'ID':1000, 'province':'AB', 'income':12000}
r2 = {'ID':1212, 'province':'AB', 'income':43000}
r3 = {'ID':1357, 'province':'BC', 'income':95000}
r4 = {'ID':4908, 'province':'BC', 'income':79500}
dataList = [r1, r2, r3, r4]
index_temp = []

for x in dataList:
    index_temp.append(x['ID'])

df = DataFrame(dataList, index=index_temp,
               columns=['province', 'income'])
df.head()

province  income
1000       AB   12000
1212       AB   43000
1357       BC   95000
4908       BC   79500

### Loading data from a csv file

In [52]:
basedf = pd.read_csv('csv_hil/ss13hil.csv')
basedf[['SERIALNO', 'PUMA00', 'PUMA10', 'ST', 'ADJHSG', 'ADJINC',
        'WGTP', 'NP', 'TYPE', 'ACR', 'AGS', 'BATH', 'BDSP',
        'BLD', 'BUS', 'CONP', 'ELEP', 'FS', 'FULP']].head()

SERIALNO  PUMA00  PUMA10  ST   ADJHSG   ADJINC  WGTP  NP  TYPE  ACR  \
0  2009000000061    3515      -9  17  1086032  1085467    36   0     1  NaN   
1  2009000000075    1000      -9  17  1086032  1085467     6   1     1  1.0   
2  2009000000108    3402      -9  17  1086032  1085467    15   3     1  1.0   
3  2009000000132    3510      -9  17  1086032  1085467    60   4     1  1.0   
4  2009000000150    3518      -9  17  1086032  1085467    37   3     1  1.0   

   AGS  BATH  BDSP  BLD  BUS  CONP   ELEP   FS  FULP  
0  NaN   2.0   2.0  8.0  NaN   0.0    NaN  NaN   NaN  
1  NaN   1.0   3.0  1.0  2.0   0.0  200.0  2.0   2.0  
2  NaN   1.0   3.0  2.0  2.0   0.0   80.0  2.0   2.0  
3  NaN   1.0   3.0  2.0  2.0   0.0    1.0  2.0   2.0  
4  NaN   1.0   3.0  2.0  2.0   0.0  200.0  1.0   2.0

In [53]:
basedf = pd.read_csv('csv_hil/ss13hil.csv', index_col='SERIALNO',
                     usecols=['SERIALNO', 'PUMA00', 'PUMA10', 'ST',
                              'ADJHSG', 'ADJINC', 'WGTP', 'NP', 'TYPE', 'ACR',
                              'AGS', 'BATH', 'BDSP', 'BLD', 'BUS', 'CONP', 'ELEP',
                              'FS', 'FULP'])
basedf.head()

PUMA00  PUMA10  ST   ADJHSG   ADJINC  WGTP  NP  TYPE  ACR  AGS  \
SERIALNO                                                                        
2009000000061    3515      -9  17  1086032  1085467    36   0     1  NaN  NaN   
2009000000075    1000      -9  17  1086032  1085467     6   1     1  1.0  NaN   
2009000000108    3402      -9  17  1086032  1085467    15   3     1  1.0  NaN   
2009000000132    3510      -9  17  1086032  1085467    60   4     1  1.0  NaN   
2009000000150    3518      -9  17  1086032  1085467    37   3     1  1.0  NaN   

               BATH  BDSP  BLD  BUS  CONP   ELEP   FS  FULP  
SERIALNO                                                     
2009000000061   2.0   2.0  8.0  NaN   0.0    NaN  NaN   NaN  
2009000000075   1.0   3.0  1.0  2.0   0.0  200.0  2.0   2.0  
2009000000108   1.0   3.0  2.0  2.0   0.0   80.0  2.0   2.0  
2009000000132   1.0   3.0  2.0  2.0   0.0    1.0  2.0   2.0  
2009000000150   1.0   3.0  2.0  2.0   0.0  200.0  1.0   2.0

### Accessing Data from a DataFrame

In [54]:
# Access a row
basedf.loc[[2009000000061]]

PUMA00  PUMA10  ST   ADJHSG   ADJINC  WGTP  NP  TYPE  ACR  AGS  \
SERIALNO                                                                        
2009000000061    3515      -9  17  1086032  1085467    36   0     1  NaN  NaN   

               BATH  BDSP  BLD  BUS  CONP  ELEP  FS  FULP  
SERIALNO                                                   
2009000000061   2.0   2.0  8.0  NaN   0.0   NaN NaN   NaN

In [55]:
# Change the value NP in a given row
basedf.loc[[2009000000061],'NP'] = 1
basedf.loc[[2009000000061]]

PUMA00  PUMA10  ST   ADJHSG   ADJINC  WGTP  NP  TYPE  ACR  AGS  \
SERIALNO                                                                        
2009000000061    3515      -9  17  1086032  1085467    36   1     1  NaN  NaN   

               BATH  BDSP  BLD  BUS  CONP  ELEP  FS  FULP  
SERIALNO                                                   
2009000000061   2.0   2.0  8.0  NaN   0.0   NaN NaN   NaN

In [56]:
# Access both rows
basedf.loc[[2009000000061,2009000000075]]

PUMA00  PUMA10  ST   ADJHSG   ADJINC  WGTP  NP  TYPE  ACR  AGS  \
SERIALNO                                                                        
2009000000061    3515      -9  17  1086032  1085467    36   1     1  NaN  NaN   
2009000000075    1000      -9  17  1086032  1085467     6   1     1  1.0  NaN   

               BATH  BDSP  BLD  BUS  CONP   ELEP   FS  FULP  
SERIALNO                                                     
2009000000061   2.0   2.0  8.0  NaN   0.0    NaN  NaN   NaN  
2009000000075   1.0   3.0  1.0  2.0   0.0  200.0  2.0   2.0

In [57]:
# Adding a new column or field
basedf['newField'] = 22
basedf[['newField']].head()

newField
SERIALNO               
2009000000061        22
2009000000075        22
2009000000108        22
2009000000132        22
2009000000150        22

In [58]:
# Grab the first 5 rows
basedf.iloc[:5]

PUMA00  PUMA10  ST   ADJHSG   ADJINC  WGTP  NP  TYPE  ACR  AGS  \
SERIALNO                                                                        
2009000000061    3515      -9  17  1086032  1085467    36   1     1  NaN  NaN   
2009000000075    1000      -9  17  1086032  1085467     6   1     1  1.0  NaN   
2009000000108    3402      -9  17  1086032  1085467    15   3     1  1.0  NaN   
2009000000132    3510      -9  17  1086032  1085467    60   4     1  1.0  NaN   
2009000000150    3518      -9  17  1086032  1085467    37   3     1  1.0  NaN   

               BATH  BDSP  BLD  BUS  CONP   ELEP   FS  FULP  newField  
SERIALNO                                                               
2009000000061   2.0   2.0  8.0  NaN   0.0    NaN  NaN   NaN        22  
2009000000075   1.0   3.0  1.0  2.0   0.0  200.0  2.0   2.0        22  
2009000000108   1.0   3.0  2.0  2.0   0.0   80.0  2.0   2.0        22  
2009000000132   1.0   3.0  2.0  2.0   0.0    1.0  2.0   2.0        22  
2009000000150   1.0   3.0  2.0  2.0   0.0  200.0  1.0   2.0        22

### Problems 1

1) Load the ss13hil.csv file to a DataFrame including only the columns: ’SERIALNO’, ’PUMA00’, ’PUMA10’, ’HUPARC’, ’KIT’, ’LNGI’, ’MULTG’, ’MV’, ’NOC’, ’NPF’, ’NPP’, ’NR’, ’NRC’, ’OCPIP’, ’WGTP’ and force SERIALNO to be the index

In [59]:
prob_df = pd.read_csv('csv_hil/ss13hil.csv', index_col='SERIALNO',
                       usecols=['SERIALNO', 'PUMA00', 'PUMA10', 'HUPARC',
                                'KIT', 'LNGI', 'MULTG', 'MV', 'NOC', 'NPF',
                                'NPP', 'NR', 'NRC', 'OCPIP', 'WGTP'])

2) Look up the 10th through 12th rows of the DataFrame (by index location)

In [60]:
prob_df.iloc[10:13]

PUMA00  PUMA10  WGTP  HUPARC  KIT  LNGI  MULTG   MV  NOC  NPF  \
SERIALNO                                                                       
2009000000308    3201      -9    59     NaN  1.0   NaN    NaN  NaN  NaN  NaN   
2009000000335    2700      -9    28     4.0  1.0   1.0    1.0  3.0  0.0  NaN   
2009000000353    3404      -9    40     NaN  1.0   NaN    NaN  NaN  NaN  NaN   

               NPP   NR  NRC  OCPIP  
SERIALNO                             
2009000000308  NaN  NaN  NaN    NaN  
2009000000335  0.0  0.0  0.0    NaN  
2009000000353  NaN  NaN  NaN    NaN

3) Use the SERIALNO values obtained for the 10th through 12th rows and construct a filter by index value that returns the same rows 

In [61]:
serial_numbers = prob_df.iloc[10:13].reset_index()['SERIALNO'].values

4) Select these rows again with only the columns ’HUPARC’, ’KIT’, ’LNGI’, ’MULTG’, ’MV’

In [62]:
filtered_df = prob_df.loc[serial_numbers, ['HUPARC', 'KIT', 'LNGI', 'MULTIG', 'MV']]
filtered_df.head()

/home/kenny/miniconda3/lib/python3.6/site-packages/pandas/core/indexing.py:1494: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


HUPARC  KIT  LNGI  MULTIG   MV
SERIALNO                                     
2009000000308     NaN  1.0   NaN     NaN  NaN
2009000000335     4.0  1.0   1.0     NaN  3.0
2009000000353     NaN  1.0   NaN     NaN  NaN

### Problems 2

1) Starting from the filtered DataFrame that you created above, assign this a new variable (say dataview1) 

In [63]:
filtered_df['dataview1'] = 0
filtered_df.head()

HUPARC  KIT  LNGI  MULTIG   MV  dataview1
SERIALNO                                                
2009000000308     NaN  1.0   NaN     NaN  NaN          0
2009000000335     4.0  1.0   1.0     NaN  3.0          0
2009000000353     NaN  1.0   NaN     NaN  NaN          0

2) Take the same filtered DataFrame and assign it to a second variable (say df2) and this time use the .copy() command (usage: df2=df1.loc[[something],[some cols]].copy()) 

In [64]:
df2 = filtered_df.copy()

3) Inspect your two “new” dataframes and confirm that they are the same as your original filtered data

In [65]:
df2.head()

HUPARC  KIT  LNGI  MULTIG   MV  dataview1
SERIALNO                                                
2009000000308     NaN  1.0   NaN     NaN  NaN          0
2009000000335     4.0  1.0   1.0     NaN  3.0          0
2009000000353     NaN  1.0   NaN     NaN  NaN          0

In [66]:
filtered_df.head()

HUPARC  KIT  LNGI  MULTIG   MV  dataview1
SERIALNO                                                
2009000000308     NaN  1.0   NaN     NaN  NaN          0
2009000000335     4.0  1.0   1.0     NaN  3.0          0
2009000000353     NaN  1.0   NaN     NaN  NaN          0

4) We will now explore how they are different. Change a value in the basedf for one of your filtered columns and rows. Now examine your two derived DataFrames to see if your change propagated.

In [67]:
prob_df.loc[[2009000000308], 'MV'] = 1.0
prob_df.iloc[10:13]

PUMA00  PUMA10  WGTP  HUPARC  KIT  LNGI  MULTG   MV  NOC  NPF  \
SERIALNO                                                                       
2009000000308    3201      -9    59     NaN  1.0   NaN    NaN  1.0  NaN  NaN   
2009000000335    2700      -9    28     4.0  1.0   1.0    1.0  3.0  0.0  NaN   
2009000000353    3404      -9    40     NaN  1.0   NaN    NaN  NaN  NaN  NaN   

               NPP   NR  NRC  OCPIP  
SERIALNO                             
2009000000308  NaN  NaN  NaN    NaN  
2009000000335  0.0  0.0  0.0    NaN  
2009000000353  NaN  NaN  NaN    NaN

In [68]:
filtered_df.head()

HUPARC  KIT  LNGI  MULTIG   MV  dataview1
SERIALNO                                                
2009000000308     NaN  1.0   NaN     NaN  NaN          0
2009000000335     4.0  1.0   1.0     NaN  3.0          0
2009000000353     NaN  1.0   NaN     NaN  NaN          0

In [69]:
df2.head()

HUPARC  KIT  LNGI  MULTIG   MV  dataview1
SERIALNO                                                
2009000000308     NaN  1.0   NaN     NaN  NaN          0
2009000000335     4.0  1.0   1.0     NaN  3.0          0
2009000000353     NaN  1.0   NaN     NaN  NaN          0

The change in the original dataFrame propogates to the filtered version. This is because the filtered version is just a subset of the regular one. The copy however, doesn't experience this propogation as it was a copy of the original filtered version prior to the change.

5) Conversely, make a different change to each of the two derived DataFrames and check the original to see if it propagated back.

In [70]:
df2.loc[[2009000000353], 'MV'] = 1.0
df2.head()

HUPARC  KIT  LNGI  MULTIG   MV  dataview1
SERIALNO                                                
2009000000308     NaN  1.0   NaN     NaN  NaN          0
2009000000335     4.0  1.0   1.0     NaN  3.0          0
2009000000353     NaN  1.0   NaN     NaN  1.0          0

In [71]:
filtered_df.loc[[2009000000353], 'MULTIG'] = 1.0
filtered_df.head()

HUPARC  KIT  LNGI  MULTIG   MV  dataview1
SERIALNO                                                
2009000000308     NaN  1.0   NaN     NaN  NaN          0
2009000000335     4.0  1.0   1.0     NaN  3.0          0
2009000000353     NaN  1.0   NaN     1.0  NaN          0

In [72]:
prob_df.iloc[10:13]

PUMA00  PUMA10  WGTP  HUPARC  KIT  LNGI  MULTG   MV  NOC  NPF  \
SERIALNO                                                                       
2009000000308    3201      -9    59     NaN  1.0   NaN    NaN  1.0  NaN  NaN   
2009000000335    2700      -9    28     4.0  1.0   1.0    1.0  3.0  0.0  NaN   
2009000000353    3404      -9    40     NaN  1.0   NaN    NaN  NaN  NaN  NaN   

               NPP   NR  NRC  OCPIP  
SERIALNO                             
2009000000308  NaN  NaN  NaN    NaN  
2009000000335  0.0  0.0  0.0    NaN  
2009000000353  NaN  NaN  NaN    NaN

The change in filtered_df propogated to the original dataFrame. Again the changes to the dataFrame made using the copy command was isolated and any changes made to it did not effect the other dataFrames.

- This is the difference between deep and shallow copies. Shallow copies are made by reference only and so changes propagate while deepcopies are completely independent objects. The upside of deepcopies is that they have no entanglements or side effects related to other objects. They only change when you change them. The downside is that they require a separate memory allocation so they quickly become prohibitive when you are working with very large data sets.


### Querying DataFrames

- The methods for data access that we have described so far don’t lend themselves to searching for rows based on meaningful data
- In this section, we will describe complex methods for selecting subsets of a DataFrame
- We will focus on two methods: (1) query (2) Boolean Indexing
- The two methods are essentially equivalent in simple cases but Boolean Indexing can be much more general

#### Query
- query takes a text string argument in the form (roughly) of a SQL WHERE clause
- Column names need to be referenced without quoting so suitable single-word names are needed
- https://pandas.pydata.org/pandas-docs/version/0.22/indexing.html#indexing-query

In [73]:
basedf.query('PUMA00 == 3515')

PUMA00  PUMA10  ST   ADJHSG   ADJINC  WGTP  NP  TYPE  ACR  AGS  \
SERIALNO                                                                        
2009000000061    3515      -9  17  1086032  1085467    36   1     1  NaN  NaN   
2009000002489    3515      -9  17  1086032  1085467    15   1     1  2.0  1.0   
2009000002611    3515      -9  17  1086032  1085467    49   2     1  NaN  NaN   
2009000002724    3515      -9  17  1086032  1085467    45   1     1  1.0  NaN   
2009000006025    3515      -9  17  1086032  1085467    17   2     1  NaN  NaN   
2009000009853    3515      -9  17  1086032  1085467    14   4     1  1.0  NaN   
2009000010773    3515      -9  17  1086032  1085467    18   2     1  1.0  NaN   
2009000012599    3515      -9  17  1086032  1085467    60   4     1  1.0  NaN   
2009000012695    3515      -9  17  1086032  1085467    44   3     1  1.0  NaN   
2009000013780    3515      -9  17  1086032  1085467    20   3     1  NaN  NaN   
2009000021230    3515      -9  17  1086032  1085467    18   1     1  NaN  NaN   
2009000022438    3515      -9  17  1086032  1085467     0   1     2  NaN  NaN   
2009000022715    3515      -9  17  1086032  1085467    33   1     1  NaN  NaN   
2009000022871    3515      -9  17  1086032  1085467    27   7     1  1.0  NaN   
2009000023991    3515      -9  17  1086032  1085467    34   1     1  NaN  NaN   
2009000024254    3515      -9  17  1086032  1085467    15   4     1  NaN  NaN   
2009000026127    3515      -9  17  1086032  1085467    24   1     1  NaN  NaN   
2009000026822    3515      -9  17  1086032  1085467    34   0     1  NaN  NaN   
2009000027183    3515      -9  17  1086032  1085467    23   2     1  NaN  NaN   
2009000027392    3515      -9  17  1086032  1085467    37   0     1  NaN  NaN   
2009000028444    3515      -9  17  1086032  1085467    21   1     1  NaN  NaN   
2009000028568    3515      -9  17  1086032  1085467    14   0     1  1.0  NaN   
2009000030494    3515      -9  17  1086032  1085467    39   6     1  NaN  NaN   
2009000031347    3515      -9  17  1086032  1085467    31   1     1  NaN  NaN   
2009000032751    3515      -9  17  1086032  1085467     0   1     2  NaN  NaN   
2009000032821    3515      -9  17  1086032  1085467    40   0     1  NaN  NaN   
2009000039391    3515      -9  17  1086032  1085467    41   1     1  NaN  NaN   
2009000039418    3515      -9  17  1086032  1085467    17   1     1  NaN  NaN   
2009000042011    3515      -9  17  1086032  1085467    33   3     1  NaN  NaN   
2009000046340    3515      -9  17  1086032  1085467    40   4     1  NaN  NaN   
...               ...     ...  ..      ...      ...   ...  ..   ...  ...  ...   
2011001440178    3515      -9  17  1035725  1054614     0   1     3  NaN  NaN   
2011001443385    3515      -9  17  1035725  1054614    11   1     1  NaN  NaN   
2011001443607    3515      -9  17  1035725  1054614     0   1     2  NaN  NaN   
2011001451083    3515      -9  17  1035725  1054614     8   1     1  1.0  NaN   
2011001451956    3515      -9  17  1035725  1054614    38   6     1  NaN  NaN   
2011001452314    3515      -9  17  1035725  1054614    63   1     1  NaN  NaN   
2011001452423    3515      -9  17  1035725  1054614    17   1     1  NaN  NaN   
2011001455146    3515      -9  17  1035725  1054614    21   1     1  NaN  NaN   
2011001455997    3515      -9  17  1035725  1054614     0   1     2  NaN  NaN   
2011001458835    3515      -9  17  1035725  1054614    14   2     1  NaN  NaN   
2011001459951    3515      -9  17  1035725  1054614    31   2     1  NaN  NaN   
2011001462339    3515      -9  17  1035725  1054614    11   4     1  NaN  NaN   
2011001462348    3515      -9  17  1035725  1054614    27   6     1  1.0  NaN   
2011001462403    3515      -9  17  1035725  1054614    31   2     1  1.0  NaN   
2011001462832    3515      -9  17  1035725  1054614    23   0     1  NaN  NaN   
2011001465772    3515      -9  17  1035725  1054614     6   1     1  NaN  NaN   
2011001472550    3515      -9  17  1035725  10

- The query functionality can work between fields.
- However, the only operators that I would rely on are (==, !=, <, >, <=, >=, &, | )
- query() is by default evaluated using the numexpr engine, which outperforms pure python on DataFrames of more than 200,000 rows

In [74]:
basedf.query('BDSP == NP')

PUMA00  PUMA10  ST   ADJHSG   ADJINC  WGTP  NP  TYPE  ACR  AGS  \
SERIALNO                                                                        
2009000000108    3402      -9  17  1086032  1085467    15   3     1  1.0  NaN   
2009000000150    3518      -9  17  1086032  1085467    37   3     1  1.0  NaN   
2009000000225    3402      -9  17  1086032  1085467    19   2     1  NaN  NaN   
2009000000256     600      -9  17  1086032  1085467    26   2     1  NaN  NaN   
2009000000335    2700      -9  17  1086032  1085467    28   1     1  NaN  NaN   
2009000000461     400      -9  17  1086032  1085467    43   4     1  1.0  NaN   
2009000000496    1101      -9  17  1086032  1085467    53   2     1  NaN  NaN   
2009000000629    3001      -9  17  1086032  1085467    22   3     1  1.0  NaN   
2009000000775    3510      -9  17  1086032  1085467    24   1     1  NaN  NaN   
2009000000912    1800      -9  17  1086032  1085467     7   1     1  1.0  NaN   
2009000001130    3005      -9  17  1086032  1085467    19   1     1  NaN  NaN   
2009000001170    1000      -9  17  1086032  1085467    22   3     1  2.0  1.0   
2009000001233     200      -9  17  1086032  1085467     8   1     1  1.0  NaN   
2009000001398    3305      -9  17  1086032  1085467    13   4     1  1.0  NaN   
2009000001474    3104      -9  17  1086032  1085467    21   5     1  1.0  NaN   
2009000001515    3502      -9  17  1086032  1085467    13   2     1  NaN  NaN   
2009000001591     200      -9  17  1086032  1085467     2   4     1  1.0  NaN   
2009000001736    2700      -9  17  1086032  1085467    19   4     1  1.0  NaN   
2009000001902    3206      -9  17  1086032  1085467    17   3     1  1.0  NaN   
2009000001950    2900      -9  17  1086032  1085467    16   3     1  1.0  NaN   
2009000002087     500      -9  17  1086032  1085467     3   3     1  1.0  NaN   
2009000002113    1300      -9  17  1086032  1085467    20   2     1  2.0  1.0   
2009000002240     900      -9  17  1086032  1085467    24   2     1  NaN  NaN   
2009000002293    3510      -9  17  1086032  1085467    23   1     1  NaN  NaN   
2009000002317    3405      -9  17  1086032  1085467    12   4     1  1.0  NaN   
2009000002429    3410      -9  17  1086032  1085467    24   4     1  1.0  NaN   
2009000002483    3511      -9  17  1086032  1085467    13   2     1  NaN  NaN   
2009000002496    3206      -9  17  1086032  1085467    17   4     1  1.0  NaN   
2009000002722    1400      -9  17  1086032  1085467    14   3     1  1.0  NaN   
2009000002726    3204      -9  17  1086032  1085467    20   3     1  1.0  NaN   
...               ...     ...  ..      ...      ...   ...  ..   ...  ...  ...   
2013001488955      -9    2000  17  1000000  1007549    20   2     1  NaN  NaN   
2013001488994      -9    3521  17  1000000  1007549    15   2     1  NaN  NaN   
2013001489051      -9    2501  17  1000000  1007549     4   2     1  1.0  NaN   
2013001489062      -9    3007  17  1000000  1007549    41   2     1  1.0  NaN   
2013001489147      -9    3420  17  1000000  1007549    77   3     1  NaN  NaN   
2013001489260      -9    3502  17  1000000  1007549    11   1     1  NaN  NaN   
2013001489329      -9    2100  17  1000000  1007549     5   1     1  1.0  NaN   
2013001489749      -9    3102  17  1000000  1007549    41   1     1  NaN  NaN   
2013001489860      -9    1300  17  1000000  1007549    64   5     1  1.0  NaN   
2013001489873      -9    3205  17  1000000  1007549    49   1     1  NaN  NaN   
2013001489894      -9    3204  17  1000000  1007549    27   4     1  1.0  NaN   
2013001489972      -9    3700  17  1000000  1007549     3   2     1  1.0  NaN   
2013001489989      -9     105  17  1000000  1007549    32   1     1  1.0  NaN   
2013001490108      -9    3530  17  1000000  1007549    17   3     1  1.0  NaN   
2013001490119      -9    1701  17  1000000  1007549    17   3     1  1.0  NaN   
2013001490258      -9     300  17  1000000  1007549    13   3     1  2.0  3.0   
2013001490268      -9     501  17  1000000  10

- Arithmetic is possible although I can’t speak to its efficiency
- The use of in and not in operators as well as ==[’a’,’b’,...], although parts of this will generally be evaluated using pure python

In [75]:
basedf.query('0 < BDSP < NP & PUMA00 == 3515')

PUMA00  PUMA10  ST   ADJHSG   ADJINC  WGTP  NP  TYPE  ACR  AGS  \
SERIALNO                                                                        
2009000002611    3515      -9  17  1086032  1085467    49   2     1  NaN  NaN   
2009000013780    3515      -9  17  1086032  1085467    20   3     1  NaN  NaN   
2009000022871    3515      -9  17  1086032  1085467    27   7     1  1.0  NaN   
2009000024254    3515      -9  17  1086032  1085467    15   4     1  NaN  NaN   
2009000030494    3515      -9  17  1086032  1085467    39   6     1  NaN  NaN   
2009000046340    3515      -9  17  1086032  1085467    40   4     1  NaN  NaN   
2009000069632    3515      -9  17  1086032  1085467    30   4     1  NaN  NaN   
2009000086634    3515      -9  17  1086032  1085467    15   4     1  1.0  NaN   
2009000088409    3515      -9  17  1086032  1085467    40   5     1  NaN  NaN   
2009000124024    3515      -9  17  1086032  1085467    25   5     1  1.0  NaN   
2009000134542    3515      -9  17  1086032  1085467    37   6     1  1.0  NaN   
2009000135687    3515      -9  17  1086032  1085467    31   5     1  NaN  NaN   
2009000137681    3515      -9  17  1086032  1085467    40   5     1  NaN  NaN   
2009000143272    3515      -9  17  1086032  1085467    55   3     1  NaN  NaN   
2009000164550    3515      -9  17  1086032  1085467    42   3     1  NaN  NaN   
2009000235371    3515      -9  17  1086032  1085467    22   4     1  NaN  NaN   
2009000242105    3515      -9  17  1086032  1085467    30   4     1  NaN  NaN   
2009000261112    3515      -9  17  1086032  1085467    48   4     1  NaN  NaN   
2009000278006    3515      -9  17  1086032  1085467    15   4     1  NaN  NaN   
2009000281193    3515      -9  17  1086032  1085467    23  13     1  1.0  NaN   
2009000289745    3515      -9  17  1086032  1085467    71   3     1  NaN  NaN   
2009000290319    3515      -9  17  1086032  1085467    30   3     1  NaN  NaN   
2009000298561    3515      -9  17  1086032  1085467    16   4     1  1.0  NaN   
2009000302575    3515      -9  17  1086032  1085467    18   3     1  NaN  NaN   
2009000304973    3515      -9  17  1086032  1085467    18   6     1  1.0  NaN   
2009000310241    3515      -9  17  1086032  1085467    49   3     1  NaN  NaN   
2009000320632    3515      -9  17  1086032  1085467    30   5     1  NaN  NaN   
2009000343682    3515      -9  17  1086032  1085467    17   3     1  NaN  NaN   
2009000345878    3515      -9  17  1086032  1085467    16   5     1  1.0  NaN   
2009000347349    3515      -9  17  1086032  1085467    10   3     1  NaN  NaN   
...               ...     ...  ..      ...      ...   ...  ..   ...  ...  ...   
2011001168857    3515      -9  17  1035725  1054614    20   2     1  NaN  NaN   
2011001169212    3515      -9  17  1035725  1054614    21   4     1  NaN  NaN   
2011001176565    3515      -9  17  1035725  1054614    19   3     1  NaN  NaN   
2011001205856    3515      -9  17  1035725  1054614    15   7     1  1.0  NaN   
2011001218196    3515      -9  17  1035725  1054614    20   3     1  NaN  NaN   
2011001218409    3515      -9  17  1035725  1054614    15   3     1  NaN  NaN   
2011001234936    3515      -9  17  1035725  1054614    25   7     1  1.0  NaN   
2011001237682    3515      -9  17  1035725  1054614    24   7     1  NaN  NaN   
2011001245795    3515      -9  17  1035725  1054614    20   3     1  NaN  NaN   
2011001249889    3515      -9  17  1035725  1054614    47   3     1  NaN  NaN   
2011001253824    3515      -9  17  1035725  1054614     8   3     1  NaN  NaN   
2011001267924    3515      -9  17  1035725  1054614    28   3     1  1.0  NaN   
2011001270004    3515      -9  17  1035725  1054614     8   2     1  NaN  NaN   
2011001273174    3515      -9  17  1035725  1054614    18   4     1  NaN  NaN   
2011001275567    3515      -9  17  1035725  1054614    19   7     1  1.0  NaN   
2011001282747    3515      -9  17  1035725  1054614     8   3     1  NaN  NaN   
2011001314614    3515      -9  17  1035725  10

### Boolean Indexing

- Boolean Indexing takes advantage of the fact the any Series derived from a dataframe keeps the same index as the dataframe
- It amounts to creating a mask that only lets certain values slip through while blocking others

In [76]:
mask = (basedf['PUMA00'] == 3515)
mask[0:5]

SERIALNO
2009000000061     True
2009000000075    False
2009000000108    False
2009000000132    False
2009000000150    False
Name: PUMA00, dtype: bool

- The mask itself can be created separately and then applied

In [77]:
mask = (basedf['PUMA00'] == 3515)
basedf[mask].head()

PUMA00  PUMA10  ST   ADJHSG   ADJINC  WGTP  NP  TYPE  ACR  AGS  \
SERIALNO                                                                        
2009000000061    3515      -9  17  1086032  1085467    36   1     1  NaN  NaN   
2009000002489    3515      -9  17  1086032  1085467    15   1     1  2.0  1.0   
2009000002611    3515      -9  17  1086032  1085467    49   2     1  NaN  NaN   
2009000002724    3515      -9  17  1086032  1085467    45   1     1  1.0  NaN   
2009000006025    3515      -9  17  1086032  1085467    17   2     1  NaN  NaN   

               BATH  BDSP  BLD  BUS  CONP   ELEP   FS  FULP  newField  
SERIALNO                                                               
2009000000061   2.0   2.0  8.0  NaN   0.0    NaN  NaN   NaN        22  
2009000002489   1.0   2.0  2.0  2.0   0.0   50.0  1.0   1.0        22  
2009000002611   1.0   1.0  6.0  NaN   0.0   50.0  2.0   2.0        22  
2009000002724   1.0   3.0  2.0  2.0   0.0   40.0  2.0   2.0        22  
2009000006025   1.0   2.0  4.0  NaN   0.0  100.0  2.0   2.0        22

- The filtering logic and functions used to create the mask itself can be as complex as you like
- Anything you can write in Python can be implemented to create a mask as long as you keep the same index intact

In [78]:
def filt(x):
    if x == 1:
        return True
    if x == 2:
        return False
    if x > 2:
        return True

mask = (basedf['PUMA00'] == 3515) & (basedf['BDSP'].map(filt))
basedf[mask].head()


PUMA00  PUMA10  ST   ADJHSG   ADJINC  WGTP  NP  TYPE  ACR  AGS  \
SERIALNO                                                                        
2009000002611    3515      -9  17  1086032  1085467    49   2     1  NaN  NaN   
2009000002724    3515      -9  17  1086032  1085467    45   1     1  1.0  NaN   
2009000009853    3515      -9  17  1086032  1085467    14   4     1  1.0  NaN   
2009000010773    3515      -9  17  1086032  1085467    18   2     1  1.0  NaN   
2009000012599    3515      -9  17  1086032  1085467    60   4     1  1.0  NaN   

               BATH  BDSP  BLD  BUS  CONP   ELEP   FS  FULP  newField  
SERIALNO                                                               
2009000002611   1.0   1.0  6.0  NaN   0.0   50.0  2.0   2.0        22  
2009000002724   1.0   3.0  2.0  2.0   0.0   40.0  2.0   2.0        22  
2009000009853   1.0   4.0  2.0  2.0   0.0  150.0  2.0   2.0        22  
2009000010773   1.0   3.0  3.0  2.0   0.0  110.0  2.0   2.0        22  
2009000012599   1.0   8.0  2.0  2.0   0.0   50.0  2.0   2.0        22

### Problems 1

1) Start from an import of the PUMS csv using the columns 'SERIALNO', 'PUMA00', 'BDSP', and 'NP' (as usual with SERIALNO as the index). load this to a variable named basedf

In [79]:
basedf = pd.read_csv('csv_hil/ss13hil.csv', index_col='SERIALNO',
                     usecols=['SERIALNO', 'PUMA00', 'NP', 'BDSP'])
basedf.head()

PUMA00  NP  BDSP
SERIALNO                       
2009000000061    3515   0   2.0
2009000000075    1000   1   3.0
2009000000108    3402   3   3.0
2009000000132    3510   4   3.0
2009000000150    3518   3   3.0

2) Use the command basedf[['PUMA00']].drop duplicates() to produce a list of the unique PUMA regions from 2000.

In [80]:
unique_df = basedf[['PUMA00']].drop_duplicates()
print(len(basedf))
print(len(unique_df))
print(unique_df)

287799
88
               PUMA00
SERIALNO             
2009000000061    3515
2009000000075    1000
2009000000108    3402
2009000000132    3510
2009000000150    3518
2009000000249    2000
2009000000256     600
2009000000268    3410
2009000000277    3502
2009000000308    3201
2009000000335    2700
2009000000353    3404
2009000000360     700
2009000000372    3003
2009000000402     800
2009000000461     400
2009000000496    1101
2009000000539    1201
2009000000542    1400
2009000000567    2500
2009000000592     101
2009000000629    3001
2009000000730    2100
2009000000733    1600
2009000000787    1202
2009000000912    1800
2009000000923    3101
2009000001130    3005
2009000001143    1900
2009000001144    3202
...               ...
2009000002941    3409
2009000003065    3501
2009000003580    3413
2009000003661    2400
2009000003667    2300
2009000003802    3408
2009000003803    3401
2009000003936    3507
2009000004197     102
2009000004391    3103
2009000004469    2800
2009000004514    1500


3) Using the query command, select only those rows where the PUMA region number matches one specific one that you chose to work with from the previous step. How many records are returned? (look below the readout of sample rows to see a number) Repeat this for 4 different PUMAs and compare the counts returned for each. (what is the total?)

In [81]:
count_3515 = len(basedf.query('PUMA00 == 3515'))
count_3003 = len(basedf.query('PUMA00 == 3003'))
count_1400 = len(basedf.query('PUMA00 == 1400'))
count_3502 = len(basedf.query('PUMA00 == 3502'))
print(count_3515)
print(count_3003)
print(count_1400)
print(count_3502)

count_sum = count_3515 + count_3003 + count_1400 + count_3502
print(count_sum)

1968
1371
2812
2585
8736


### Problems 2

1) Write a query using the OR operator | that includes the records for all 4 of the PUMA regions that you examined above. Check that the count of rows agrees with the total you just obtained. 

In [82]:
PUMA00_check = 'PUMA00 == 3515 | PUMA00 == 3003 | PUMA00 == 1400 | PUMA00 == 3502'
combined_query = basedf.query(PUMA00_check)
print(len(combined_query))

8736


2) Extend your query using additional parentheses and the AND operator & (or and if you prefer) to select off those housing records that are in one of those 4 regions and have more than 4 people living in the residence.

In [83]:
NP_check = 'NP > 4'

combined_check = "(" + PUMA00_check + ") & " + NP_check
# print(combined_check)

combined_query = basedf.query(combined_check)
# print(combined_query)
print(len(combined_query))
combined_query.head()

493


PUMA00  NP  BDSP
SERIALNO                       
2009000022871    3515   7   4.0
2009000024086    1400   5   3.0
2009000030494    3515   6   2.0
2009000032409    3003   9   3.0
2009000061426    1400   5   3.0

3) Write a function that implements all of the PUMA logic and use the .map(functionName) operation demonstrated above to produce a Boolean Index mask for the PUMA

In [84]:
def PUMA00_filt(x):
    if x in [3515, 3003, 1400, 3502]:
        return True
    else:
        return False  

PUMA00_mask = basedf['PUMA00'].map(PUMA00_filt)
PUMA00_masked = basedf[PUMA00_mask]
print(len(PUMA00_masked))

8736


4) Write a second boolean index mask using the NP> 4 condition and combine it with the mask you just created to produce a single mask that does the work of your earlier query. 

In [85]:
def NP_filt(x):
    if x > 4:
        return True
    else:
        return False
        
combined_mask = (basedf['NP'].map(NP_filt)) & (basedf['PUMA00'].map(PUMA00_filt))
combined_masked = basedf[combined_mask]
print(len(combined_masked))

493


5) Apply the mask to get the corresponding rows and check by quick inspection if it agrees with your earlier result (we will come back to how you can check this more precisely in the next section)

In [86]:
combined_query.head()

PUMA00  NP  BDSP
SERIALNO                       
2009000022871    3515   7   4.0
2009000024086    1400   5   3.0
2009000030494    3515   6   2.0
2009000032409    3003   9   3.0
2009000061426    1400   5   3.0

In [87]:
combined_masked.head()

PUMA00  NP  BDSP
SERIALNO                       
2009000022871    3515   7   4.0
2009000024086    1400   5   3.0
2009000030494    3515   6   2.0
2009000032409    3003   9   3.0
2009000061426    1400   5   3.0

In [88]:
len(combined_query) == len(combined_masked)

True

The first 5 rows of both filtering sections agree and the lengths of both dataFrames are identical. This quick inspection suggests that the two dataFrames are identical.

### Combining DataFrames

- Just as linear algebraic operations are used to combine ndarrays, relational operators are used to combine DataFrames
- SQL operations like LEFT JOIN, INNER JOIN, UNION, INTERSECT, SELECT DISTINCT, GROUP BY and APPLY all have realizations as pandas operations
- In this section we will discuss the JOIN and UNION operations
- Pandas is meant to handle messy, inconsistent data and help in making it consistent
- Anywhere that a SQL operation would assume clean or unique data, Pandas operations are a little more complex because they are meant to allow for reality
- General Reference: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html


#### concat also known as UNION and sometimes cheap join
- concat provides a way to append data to the end of a DataFrame or to append columns to existing rows
- In its simplest form, it “adds rows” to the table, forcing agreement between the columns (by column name) where possible
- concat becomes subtle when using the option axis=1

#### concat as JOIN

- concat accepts a list of DataFrames as its only required argument
- If the indexes are completely disjoint and the column names are the same, that outcome is identical to that of UNION from SQL

In [89]:
df1 = DataFrame({'a':[1, 2, 3], 'b':[4, 5, 6]}, index=['x','y','z'])
df2 = DataFrame({'a':[7, 8, 9], 'b':[10, 11, 12]}, index=['u','v','w'])
pd.concat([df1, df2])

a   b
x  1   4
y  2   5
z  3   6
u  7  10
v  8  11
w  9  12

#### concat as UNION for data with different columns

- If the indexes are completely disjoint and the column names are not the same, that outcome differs from that of UNION from SQL in that it is still permitted but the non-matching columns are all included and filled in with NULLS (or in pandas language np.nan)

In [90]:
df1 = DataFrame({'a':[1, 2, 3], 'b':[4, 5, 6]}, index=['x','y','z'])
df2 = DataFrame({'a':[7, 8, 9], 'c':[10, 11, 12]}, index=['u','v','w'])
pd.concat([df1, df2])

/home/kenny/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until


a    b     c
x  1  4.0   NaN
y  2  5.0   NaN
z  3  6.0   NaN
u  7  NaN  10.0
v  8  NaN  11.0
w  9  NaN  12.0

#### concat as JOIN

- If the indexes are overlapping and the column names are not the same and axis=1 is used, that is identical to that of INNER JOIN from SQL

In [91]:
df1 = DataFrame({'a':[1, 2, 3], 'b':[4, 5, 6]}, index=['x','y','z'])
df2 = DataFrame({'c':[7, 8, 9], 'd':[10, 11, 12]}, index=['x','y','z'])
pd.concat([df1, df2], axis=1)

a  b  c   d
x  1  4  7  10
y  2  5  8  11
z  3  6  9  12

#### concat as ????

- For repeated indexes UNIONing on axis=0 or repeated columns JOINing on axis=1, concat attempts to preserve as much data as possible
- The result can be a little bit bizzarre and getting back something unambiguous may mean reindexing or renaming columns
- It is better to avoid this situation altogether if possible

In [92]:
df1 = DataFrame({'a':[1, 2, 3], 'b':[4, 5, 6]}, index=['x','y','z'])
df2 = DataFrame({'c':[7, 8, 9], 'd':[10, 11, 12]}, index=['x','y','z'])
pd.concat([df1, df2])

/home/kenny/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until


a    b    c     d
x  1.0  4.0  NaN   NaN
y  2.0  5.0  NaN   NaN
z  3.0  6.0  NaN   NaN
x  NaN  NaN  7.0  10.0
y  NaN  NaN  8.0  11.0
z  NaN  NaN  9.0  12.0

#### merge as JOIN

- merge is a holistic JOIN operator
- Like SQL JOINs, the options for using it are complex and take a great deal of practice to master
- We will focus on two options: on= and how=
- on determines the common column used to join the two together (a list of common columns can be specified)
- note that the indexes are not preserved. To keep them .reset index() before joining and then set the index from that column after or join on index (not covered here)

In [93]:
df1 = DataFrame({'a':[1, 2, 3], 'b':[4, 5, 6]}, index=['x','y','z'])
df2 = DataFrame({'a':[1, 2, 3], 'c':[10, 11, 12]}, index=['u','v','w'])
pd.merge(df1, df2, on='a')

a  b   c
0  1  4  10
1  2  5  11
2  3  6  12

#### merge as INNER JOIN

- how can be set to left, right, inner, or outer
- The left on and right on options specify the matching columns on the left and right join tables if they have different names
- Note that the default value of how is inner and this will filter out non-matching rows symmetrically

In [94]:
df1 = DataFrame({'a1':[1, 2, 3], 'b':[4, 5, 6]})
df2 = DataFrame({'a2':[1, 2, 7], 'c':[10, 11, 12]})
pd.merge(df1, df2, how='inner', left_on='a1', right_on='a2')

a1  b  a2   c
0   1  4   1  10
1   2  5   2  11

#### merge as LEFT JOIN

- By setting how to left the merge preserves columns in the first listed DataFrame
- This leaves np.nan in the columns from the second table when no matches are found

In [95]:
df1 = DataFrame({'a1':[1, 2, 3], 'b':[4, 5, 6]})
df2 = DataFrame({'a2':[1, 2, 7], 'c':[10, 11, 12]})
pd.merge(df1, df2, how='left', left_on='a1', right_on='a2')

a1  b   a2     c
0   1  4  1.0  10.0
1   2  5  2.0  11.0
2   3  6  NaN   NaN

#### merge as FULL INNER JOIN

- An outer join keeps non-matched rows from both tables, filling with np.nan as needed

In [96]:
df1 = DataFrame({'a1':[1, 2, 3], 'b':[4, 5, 6]})
df2 = DataFrame({'a2':[1, 2, 7], 'c':[10, 11, 12]})
pd.merge(df1, df2, how='outer', left_on='a1', right_on='a2')

a1    b   a2     c
0  1.0  4.0  1.0  10.0
1  2.0  5.0  2.0  11.0
2  3.0  6.0  NaN   NaN
3  NaN  NaN  7.0  12.0

#### merge as multi-key JOIN

- By passing a list to each of the on options, the corresponding keys are matched sequentially
- In this case two rows are found to match if and only if the value of a1 matches a2 and key1 matches key2

In [97]:
df1 = DataFrame({'a1':[1, 2, 3],'key1':['R', 'R', 'C'] ,'b':[4, 5, 6]})
df2 = DataFrame({'a2':[1, 2, 7],'key2':['R', 'D', 'C'], 'c':[10, 11, 12]})
pd.merge(df1, df2, how='outer', left_on=['a1', 'key1'], right_on=['a2', 'key2'])

a1 key1    b   a2 key2     c
0  1.0    R  4.0  1.0    R  10.0
1  2.0    R  5.0  NaN  NaN   NaN
2  3.0    C  6.0  NaN  NaN   NaN
3  NaN  NaN  NaN  2.0    D  11.0
4  NaN  NaN  NaN  7.0    C  12.0

### Problems 1

1) Return to the slide “concat as ???” and run the code in it. Perform a similar experiment by altering the column names in df2 to match those in df1 and run it again. Finally, change the axis of concatenation to be axis=1 and run it a third time.

In [98]:
# Running the code directly from the slide
df1 = DataFrame({'a':[1, 2, 3], 'b':[4, 5, 6]}, index=['x','y','z'])
df2 = DataFrame({'c':[7, 8, 9], 'd':[10, 11, 12]}, index=['x','y','z'])
pd.concat([df1, df2])

/home/kenny/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  after removing the cwd from sys.path.


a    b    c     d
x  1.0  4.0  NaN   NaN
y  2.0  5.0  NaN   NaN
z  3.0  6.0  NaN   NaN
x  NaN  NaN  7.0  10.0
y  NaN  NaN  8.0  11.0
z  NaN  NaN  9.0  12.0

In [99]:
# Modifying the code to make the columns in df2 match df1
df1 = DataFrame({'a':[1, 2, 3], 'b':[4, 5, 6]}, index=['x','y','z'])
df2 = DataFrame({'a':[7, 8, 9], 'b':[10, 11, 12]}, index=['x','y','z'])
pd.concat([df1, df2])

a   b
x  1   4
y  2   5
z  3   6
x  7  10
y  8  11
z  9  12

In [100]:
# Changing axis to axis=1
df1 = DataFrame({'a':[1, 2, 3], 'b':[4, 5, 6]}, index=['x','y','z'])
df2 = DataFrame({'a':[7, 8, 9], 'b':[10, 11, 12]}, index=['x','y','z'])
pd.concat([df1, df2], axis=1)

a  b  a   b
x  1  4  7  10
y  2  5  8  11
z  3  6  9  12

2) Describe for yourself how concat handles matching rows and columns under different circumstances.

concat combines two dataFrames together in a very brute force way. 

- If no axis is specified, try to match ONLY the columns.
    - If the columns do not match, extend the dataFrame to have sufficient columns to accomodate new data
    - If columns match then append the new data to the bottom of the dataFrame
- If axis=1 is specified, try to match ONLY the rows.
    - If the rows do not match, extend the dataFrame to have sufficient rows to accomodate new data
    - If rows match then append the new data to the right of the dataFrame.
    
concat only compares the headers of the axis specified. If the headers don't match, extend dataFrame, if headers do match then append the new data accordingly

3) Start from an import of the PUMS csv using the columns 'SERIALNO', 'PUMA00','WGTP', 'WGTP1', 'RMSP', 'BDSP', and 'NP' (as usual with SERIALNO as the index). load this to a variable named basedf

In [101]:
basedf = pd.read_csv('csv_hil/ss13hil.csv', index_col='SERIALNO',
                     usecols=[ 'SERIALNO', 'PUMA00','WGTP', 'WGTP1', 'RMSP', 'BDSP', 'NP'])

4) Make a list of 10 PUMA00 values

In [102]:
unique_PUMA00 = basedf[['PUMA00']].drop_duplicates()
PUMA00_list = unique_PUMA00[:10]['PUMA00'].values
print(PUMA00_list)

[3515 1000 3402 3510 3518 2000  600 3410 3502 3201]


5) Create an empty DataFrame with the columns 'PUMA00', 'WGTP', 'WGTP1' with the statement newdf=DataFrame('PUMA00':[],'WGTP':[], 'WGTP1':[] )

In [103]:
newdf = DataFrame({'PUMA00':[],'WGTP':[],'WGTP1':[]})
print(newdf)

Empty DataFrame
Columns: [PUMA00, WGTP, WGTP1]
Index: []


### Problems 2

1) Write a for loop that iterates over the list of PUMA00 values you just made and for each value queries basedf for the matching PUMA00 records, copies the resulting DataFrame and stores it to a temporary variable. Finally, the loop should concat the DataFrame to you just made by querying and copying to newdf.

In [104]:
for puma_val in PUMA00_list:
    puma_row = basedf.query('PUMA00 == ' + str(puma_val)).copy()
    concat_row = puma_row[['PUMA00', 'WGTP', 'WGTP1']]
    print(concat_row)
    pd.concat([newdf, concat_row])

print(newdf)

               PUMA00  WGTP  WGTP1
SERIALNO                          
2009000000061    3515    36     61
2009000002489    3515    15     15
2009000002611    3515    49     50
2009000002724    3515    45     13
2009000006025    3515    17      5
2009000009853    3515    14     12
2009000010773    3515    18     18
2009000012599    3515    60     57
2009000012695    3515    44     86
2009000013780    3515    20      6
2009000021230    3515    18     29
2009000022438    3515     0      0
2009000022715    3515    33      9
2009000022871    3515    27      9
2009000023991    3515    34     29
2009000024254    3515    15      4
2009000026127    3515    24      8
2009000026822    3515    34     58
2009000027183    3515    23     22
2009000027392    3515    37     64
2009000028444    3515    21     35
2009000028568    3515    14      4
2009000030494    3515    39     44
2009000031347    3515    31     30
2009000032751    3515     0      0
2009000032821    3515    40     11
2009000039391    351

               PUMA00  WGTP  WGTP1
SERIALNO                          
2009000000308    3201    59     23
2009000007170    3201    46     59
2009000010064    3201    17     17
2009000011441    3201    22     23
2009000014933    3201    21     39
2009000016348    3201    18     17
2009000017838    3201    23     40
2009000020316    3201    31     21
2009000020401    3201    13      4
2009000024806    3201    16     18
2009000026306    3201    17     17
2009000028787    3201    48     55
2009000029059    3201    19      6
2009000031605    3201    21      6
2009000034376    3201    14     24
2009000034457    3201    17     17
2009000035400    3201    60     63
2009000035988    3201    19     18
2009000036216    3201    23     41
2009000036295    3201    12     20
2009000037313    3201    16     17
2009000038391    3201    19      5
2009000039797    3201    13     22
2009000043710    3201    14     14
2009000048223    3201    11     10
2009000051881    3201    20      7
2009000052107    320

2) When the loop finishes you will have assembled a DataFrame equivalent to querying for records belonging to any of those 5 PUMA regions. This is prototypical of assembling a dataframe through a sequence of complex operations that you append on a single output table.

3) Test this by querying the full table for those 5 PUMA regions using the OR operators and copying the result to a new temporary DataFrame then using merge to perform and inner join between the two tables on SERIALNO (HINT use reset index() on each first to make the old index a column in each table)

If the resulting table has the same number of rows as the original two tables (and they have the same number of rows as themselves when deduplicating over SERIALNO) then they have the same set of records